os: linux
dist: focal
language: python
python:
  - "nightly"
  - 3.8
  - 3.7
install:
  - pip install --upgrade pip
  - pip install pep517
  - python -m pep517.build .
  - pip install dist/traitlets*.whl
  - pip install --pre --upgrade traitlets[test] pytest pytest-cov codecov
  - test -z ${TEST_DEPS} || pip install --upgrade ${TEST_DEPS}
  - pip freeze
script:
  - ${TEST:-py.test --cov traitlets -v traitlets}
after_success:
  - codecov
jobs:
  allow_failures:
    - python: "nightly"
  include:
    - python: 3.8
      env:
        - TEST_DEPS=ipython[test]
        - TEST=iptest
    - python: 3.8
      env:
        - TEST_DEPS=git+https://github.com/jupyter/nbconvert.git#egg=nbconvert[test]
        - TEST="py.test --pyargs nbconvert"
    - python: 3.8
      env:
        - TEST_DEPS=notebook[test]
        - TEST="nosetests --exclude selenium notebook"
    - python: 3.8
      env:
        - TEST_DEPS=ipywidgets[test]
        - TEST="pytest --pyargs ipywidgets"
