language: python
python:
    - "nightly"
    - 3.5
    - 3.4
    - 2.7
    - 3.3
    - 3.6-dev
sudo: false
install:
    - pip install .
    - pip install traitlets[test] pytest-cov codecov pytest-warnings
script:
    - py.test --cov traitlets -v traitlets
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
